// <auto-generated />
namespace Portfolio.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class adddescriptiontoproject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adddescriptiontoproject));
        
        string IMigrationMetadata.Id
        {
            get { return "201502261453308_add description to project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
