// <auto-generated />
namespace Portfolio.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class addedprojectUrltoproject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedprojectUrltoproject));
        
        string IMigrationMetadata.Id
        {
            get { return "201502262313464_added projectUrl to project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
